version: '3'
services:
  game:
    image: rock-paper-scissors
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/rock-paper-scissors
    environment:
      - GUI_ENABLED=false